### ISSUE TITLE
Footer section: Incorrect SEO footer option used.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#1]
Per scope:
SEO footer option #10

Standard implementation link:
https://github.com/titan-cebu/Aquarius-Wastewater-Management-Systems/issues/new

![image](https://cloud.githubusercontent.com/assets/11186313/7673819/2895a480-fd4d-11e4-871f-0825fde0152e.png)

**Comment by ramoncebudigital** [comment]
SEO footer option has been updated to 3.
