### ISSUE TITLE
Products page: Bullet style for the category/subcategory pages' unordered list is not consistent with other pages.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#20]
![image](https://cloud.githubusercontent.com/assets/11186313/7675428/00dd2742-fd6b-11e4-8ff6-315e11d6b652.png)

**Comment by ramoncebudigital** [comment]
working on my end. see screenshots
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/7718492/dcc309ec-fee3-11e4-9fa6-026527004400.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/7718493/dd61f25a-fee3-11e4-9e48-2c8195f89e7e.png)

**Comment by roseliesromeo** [comment]
This is OK now but not when I tested.  You can see from the screenshot.
