### ISSUE TITLE
Header Page: IPad device only:  The background blue color overlaps the site logo 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Aquarius-Wastewater-Management-Systems#22]
![header_01](https://cloud.githubusercontent.com/assets/11186386/7677411/5b86021e-fd7e-11e4-9a4f-2106646b2bc5.jpg)

**Comment by dsigue** [comment]
![header_01](https://cloud.githubusercontent.com/assets/11186386/7677411/5b86021e-fd7e-11e4-9a4f-2106646b2bc5.jpg)

**Comment by ramoncebudigital** [comment]
I think this is the same issue with https://github.com/titan-cebu/Aquarius-Wastewater-Management-Systems/issues/23
please don't repeat the issue, they are on the same section.

**Comment by dsigue** [comment]
I think they are not the same issue as they are different in behavior. Yes, the are the same section but just merely not the same issue, one just refer for social media link and the other once was just for the overlap /distorted logo layout.

**Comment by ramoncebudigital** [comment]
The main issue here is the header, but why putting all the header issues one at a time why not doing it at once.

**Comment by dsigue** [comment]
Its because that's the way our TL told us, logging all issues in one ticket causing the implementer might have some miss in fixing. That's why we log issue  in one at the time though they both the same section but we ensure they are not duplicate.

**Comment by ramoncebudigital** [comment]
yeah, I'ved seen your QA style and that's works for me. 
Thanks bro.

**Comment by dsigue** [comment]
Ok, This is noted. But would that be okay if all the issues you've mention as duplicate on this project would mark as fixed if you all fixed them all. Thanks bro.
