### ISSUE TITLE
Header Page: IPad device only:  Social media link layout not match from dekstop view- not  in the center layout

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Aquarius-Wastewater-Management-Systems#23]
![header_02](https://cloud.githubusercontent.com/assets/11186386/7677595/06121258-fd80-11e4-8d0d-a98b2336beb1.jpg)

**Comment by ramoncebudigital** [comment]
same issue with #22 
please don't repeat the issue, they are on the same section.
