### ISSUE TITLE
Admin - business details: Most field labels in the business details has Treatments] beside them.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#3]
![image](https://cloud.githubusercontent.com/assets/11186313/7674003/6fce5038-fd50-11e4-9438-5c0edd83ae50.png)

**Comment by ramoncebudigital** [comment]
Are you sure this is a bug?
If your not sure. please ask someone about this issue.

**Comment by ramoncebudigital** [comment]
This is not a bug, that is part of the shortcode.

**Comment by roseliesromeo** [comment]
haha
