### ISSUE TITLE
Product single page: Font color for price and background color for Add to Cart button isn't consistent with the preferred color scheme.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#32]
![image](https://cloud.githubusercontent.com/assets/11186313/7693879/fee1d2ee-fe0a-11e4-84d0-2e1f10641442.png)

**Comment by ramoncebudigital** [comment]
the website is not for online selling, this is for viewing products only.

**Comment by roseliesromeo** [comment]
If it is for viewing purposes, then don't allow users to display the Add to Cart and the price.

**Comment by ramoncebudigital** [comment]
This is already removed.
