### ISSUE TITLE
Home page: Page content is defaulted to expanded view.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#46]
IE7
![image](https://cloud.githubusercontent.com/assets/11186313/7694697/71ab1c8a-fe16-11e4-9fe4-ec561ebe8358.png)

**Comment by ramoncebudigital** [comment]
same issue https://github.com/titan-cebu/Aquarius-Wastewater-Management-Systems/issues/45

**Comment by roseliesromeo** [comment]
This is not a duplicate bug.  I may use the same screenshot but the issues are different. 
"Read More button could be missing but the page content is still in collapsed view" and "It could be in expanded view with the Read More button still on".
