### ISSUE TITLE
Home page - featured product section: < and > navigation button is not working.  It doesn't slide to left or right upon clicking.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#47]
IE7

**Comment by ramoncebudigital** [comment]
working on my end.

**Comment by roseliesromeo** [comment]
I am still able to replicate  the issue.
Try these steps:
1. Open the site in IE7.
2. Click the header logo.
3. Click navigation buttons in the "View are customized..." section.
