### ISSUE TITLE
Header Page: Ipad only:  Styled and designed the header layout during LOG IN window, something look good and pleasant.  Make them similar to the desktop view

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Aquarius-Wastewater-Management-Systems#48]
![mobile header_01](https://cloud.githubusercontent.com/assets/11186386/7694742/6917697e-fe17-11e4-99e1-a9b2e0e3bbc2.jpg)

**Comment by ramoncebudigital** [comment]
same issue with #22 and #23

**Comment by dsigue** [comment]
I log this issue in separate way though they are the same section so that it will be fixed as it is expected. Bug # 22 and # 23 they are somehow partially the same section but different log issues.
