### ISSUE TITLE
Product Singple Page: Mobile device : Inconsistent Gallery images layout from desktop view to Itouch 5 and samsung S4

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/Aquarius-Wastewater-Management-Systems#50]
![mobile product single_01](https://cloud.githubusercontent.com/assets/11186386/7694886/4a778330-fe19-11e4-93a2-26ff3601b01f.jpg)

**Comment by dsigue** [comment]
Problem verified still reproducible. Please take a look on the screenshot below : 

![new products_01](https://cloud.githubusercontent.com/assets/11186386/7742710/fa017d4a-ffc4-11e4-9206-cfc39edb3629.jpg)

**Comment by roseliesromeo** [comment]
Not fixed.
Spread the images across the width of the featured image; centered.

**Comment by ramoncebudigital** [comment]
Please provide screenshot.
Thanks.

**Comment by genesiscebudigital** [comment]
Please provide screenshot.
Thanks.

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/8000271/f2a16db8-0b8a-11e5-8746-bab8210a6997.png)
![image](https://cloud.githubusercontent.com/assets/11186313/8000274/f65864f2-0b8a-11e5-87bd-667fbfd9752e.png)

**Comment by roseliesromeo** [comment]
Not fixed in landscape view

**Comment by ramoncebudigital** [comment]
screenshot please...

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/8032063/dfc85314-0e05-11e5-8b70-c8f74d56d325.png)
