### ISSUE TITLE
Home: Services featured image doesn't fit the circle container.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#72]
Opera browser only.
![image](https://cloud.githubusercontent.com/assets/11186313/8100513/375976ea-103f-11e5-856e-80cdfe6a7a9f.png)

**Comment by ramoncebudigital** [comment]
working on my end.
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/8174179/cbf98f86-140b-11e5-8a08-82b19d1bd4d9.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/8174180/cc241436-140b-11e5-9bc8-f98c71868e4d.png)

**Comment by roseliesromeo** [comment]
This is a bug in Opera older version.
