### ISSUE TITLE
Banner section: Corners of the banner are not rounded.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#73]
Opera browser only
![image](https://cloud.githubusercontent.com/assets/11186313/8100542/ef88eb2e-103f-11e5-8ca7-8e7d2bd3ef2e.png)

**Comment by ramoncebudigital** [comment]
working on my end.
![screenshot_3](https://cloud.githubusercontent.com/assets/11186436/8174269/354bf2ca-140d-11e5-8186-e1dc522c477f.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/8174270/36ce1bb4-140d-11e5-8d7c-09282b3577b6.png)

**Comment by roseliesromeo** [comment]
This is bug in Opera older version.
