### ISSUE TITLE
Banner section: Description is not centered and it spills out of the banner description container.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#76]
Happens in IE8 only
![image](https://cloud.githubusercontent.com/assets/11186313/8177469/a6f63424-1437-11e5-8380-0965dd78ac2f.png)

**Comment by ramoncebudigital** [comment]
working on my end, tried other machines.
I think you need to wait the page to load.  :)
![screenshot_4](https://cloud.githubusercontent.com/assets/11186436/8177931/14de051c-143c-11e5-9a64-e04d14365cfa.png)
