### ISSUE TITLE
Admin - Lead-ins: Page link should include product categories in the list.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Aquarius-Wastewater-Management-Systems#8]
Clicking the lead-ins should lead to product categories.

![image](https://cloud.githubusercontent.com/assets/11186313/7674269/013d3f70-fd56-11e4-98e6-04163fc2b7cb.png)

**Comment by ramoncebudigital** [comment]
included all option, because, no option for product categories in acf page link.

**Comment by roseliesromeo** [comment]
Kindly consult Leoman about this.  There is a better solution where only list of categories will show.
